# Generated by Django 4.1.1 on 2023-09-27 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0002_alter_course_credits_alter_section_section_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
