# Generated by Django 4.1.1 on 2023-09-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='campus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RUempty.campus'),
        ),
    ]
