# Generated by Django 4.1.1 on 2023-09-29 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0004_building_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructors',
        ),
        migrations.AlterField(
            model_name='section',
            name='section_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='section',
            name='instructors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RUempty.instructor'),
        ),
    ]
