# Generated by Django 4.2.5 on 2023-09-30 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0005_instructor_remove_course_instructors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StartTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='instructors',
        ),
        migrations.AddField(
            model_name='section',
            name='instructors',
            field=models.ManyToManyField(default=None, related_name='section', to='RUempty.instructor'),
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RUempty.endtime')),
                ('start_time', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RUempty.starttime')),
            ],
            options={
                'unique_together': {('start_time', 'end_time')},
            },
        ),
    ]
