# Generated by Django 4.2.5 on 2023-09-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0006_endtime_starttime_remove_section_instructors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
