# Generated by Django 4.2.5 on 2023-09-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0009_remove_section_end_time_remove_section_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='building',
        ),
        migrations.RemoveField(
            model_name='section',
            name='campus',
        ),
    ]
