# Generated by Django 4.2.5 on 2023-09-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0010_remove_section_building_remove_section_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RUempty.subject'),
        ),
    ]
