# Generated by Django 4.2.5 on 2023-09-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0012_course_number_alter_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
