# Generated by Django 4.2.5 on 2023-09-30 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0013_remove_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='building_code',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='class_id',
            new_name='course',
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'section_number')},
        ),
        migrations.AlterField(
            model_name='section',
            name='instructors',
            field=models.ManyToManyField(default=None, related_name='sections', to='RUempty.instructor'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'number')},
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=None)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RUempty.room')),
                ('time_block', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='RUempty.timeblock')),
            ],
            options={
                'unique_together': {('time_block', 'day', 'room')},
            },
        ),
        migrations.RemoveField(
            model_name='section',
            name='day',
        ),
        migrations.RemoveField(
            model_name='section',
            name='room',
        ),
        migrations.RemoveField(
            model_name='section',
            name='time_block',
        ),
        migrations.AddField(
            model_name='section',
            name='meeting_times',
            field=models.ManyToManyField(default=None, related_name='section', to='RUempty.meetingtime'),
        ),
    ]
