# Generated by Django 4.2.5 on 2023-09-30 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0016_alter_building_name_alter_building_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'number')},
        ),
    ]
