# Generated by Django 4.2.5 on 2023-10-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0017_rename_subject_id_course_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='meeting_times',
        ),
        migrations.AddField(
            model_name='meetingtime',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='MeetingTime', to='RUempty.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='RUempty.course'),
        ),
    ]
