# Generated by Django 4.2.5 on 2023-10-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0018_remove_section_meeting_times_meetingtime_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtime',
            name='semester',
            field=models.CharField(default='92023', max_length=4),
        ),
    ]
