# Generated by Django 4.2.5 on 2023-10-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0019_meetingtime_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=92023),
        ),
        migrations.AlterField(
            model_name='meetingtime',
            name='semester',
            field=models.IntegerField(default=92023),
        ),
    ]
