# Generated by Django 4.2.5 on 2024-09-09 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0020_course_semester_alter_meetingtime_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingtime',
            name='semester',
        ),
    ]
