# Generated by Django 4.2.5 on 2024-12-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RUempty', '0021_remove_meetingtime_semester'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('subject', 'number', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='meetingtime',
            unique_together={('time_block', 'day', 'room', 'section')},
        ),
    ]
